version: '3'

services:
    web:
        build: .
        command: python3 financial/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/financial
        ports:
            - "8000:8000"
