# Generated by Django 4.0 on 2023-06-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='financial_data',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('open_price', models.FloatField(default=0)),
                ('close_price', models.FloatField(default=0)),
                ('volume', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
